### ISSUE TITLE
[Youtiba]: Hello World!

### ISSUE THREAD

**Issue by TestGithubWebUI** [Shortsub/report#1]
### Label

bug

### Operating system

Windows

### Detailed description

I tried to test this bug tracking system. And then it happens :(

The order to reproduce is:

1. Click the web link to Shortsub/report/issues
2. I am doing clicking the button `Get started`
3. We will see what happens xD
4. Compiler/Log output/Error output gives:
   ```
   INFO: Lalala
   INFO: Lululu
   ERROR: Hopefully nothing ^^
   ```

**Comment by YouDirk** [comment]
## Hahaha

Nice, works well xD

[Edit]: I let it opened for now.

**Comment by TestGithubWebUI** [comment]
:+1:

**Comment by YouDirk** [comment]
Hello World xD :speedboat: ...
